# Generated by Django 4.2.7 on 2023-11-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mercadeo1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_registrada', models.PositiveSmallIntegerField()),
                ('cantidad_vendida', models.PositiveSmallIntegerField()),
                ('ganancia', models.PositiveSmallIntegerField()),
                ('empresa_transporte', models.CharField(max_length=30)),
                ('stock_minimo', models.PositiveSmallIntegerField()),
                ('fecha_compra', models.CharField(max_length=30)),
            ],
        ),
    ]
